// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(chencangFFI)
import chencangFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_chencang_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_chencang_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureChencangBindingsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol SecretIdentityProtocol: AnyObject, Sendable {
    
    func publicIdentity()  -> PublicIdentity
    
    func serializeForLocalStorage()  -> Data
    
    func signEd25519Ik(message: Data)  -> Data
    
}
open class SecretIdentity: SecretIdentityProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_chencang_bindings_fn_clone_secretidentity(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_chencang_bindings_fn_constructor_secretidentity_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_chencang_bindings_fn_free_secretidentity(handle, $0) }
    }

    
public static func fromLocalStorage(data: Data)throws  -> SecretIdentity  {
    return try  FfiConverterTypeSecretIdentity_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_secretidentity_from_local_storage(
        FfiConverterData.lower(data),$0
    )
})
}
    

    
open func publicIdentity() -> PublicIdentity  {
    return try!  FfiConverterTypePublicIdentity_lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_secretidentity_public_identity(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func serializeForLocalStorage() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_secretidentity_serialize_for_local_storage(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func signEd25519Ik(message: Data) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_secretidentity_sign_ed25519_ik(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(message),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretIdentity: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SecretIdentity

    public static func lift(_ handle: UInt64) throws -> SecretIdentity {
        return SecretIdentity(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SecretIdentity) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretIdentity {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SecretIdentity, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretIdentity_lift(_ handle: UInt64) throws -> SecretIdentity {
    return try FfiConverterTypeSecretIdentity.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretIdentity_lower(_ value: SecretIdentity) -> UInt64 {
    return FfiConverterTypeSecretIdentity.lower(value)
}






public protocol SecretOneTimePreKeyProtocol: AnyObject, Sendable {
    
    func publicForm()  -> OneTimePreKeyPublic
    
}
open class SecretOneTimePreKey: SecretOneTimePreKeyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_chencang_bindings_fn_clone_secretonetimeprekey(self.handle, $0) }
    }
public convenience init(opkIndex: UInt32) {
    let handle =
        try! rustCall() {
    uniffi_chencang_bindings_fn_constructor_secretonetimeprekey_new(
        FfiConverterUInt32.lower(opkIndex),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_chencang_bindings_fn_free_secretonetimeprekey(handle, $0) }
    }

    

    
open func publicForm() -> OneTimePreKeyPublic  {
    return try!  FfiConverterTypeOneTimePreKeyPublic_lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_secretonetimeprekey_public_form(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretOneTimePreKey: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SecretOneTimePreKey

    public static func lift(_ handle: UInt64) throws -> SecretOneTimePreKey {
        return SecretOneTimePreKey(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SecretOneTimePreKey) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretOneTimePreKey {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SecretOneTimePreKey, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretOneTimePreKey_lift(_ handle: UInt64) throws -> SecretOneTimePreKey {
    return try FfiConverterTypeSecretOneTimePreKey.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretOneTimePreKey_lower(_ value: SecretOneTimePreKey) -> UInt64 {
    return FfiConverterTypeSecretOneTimePreKey.lower(value)
}






public protocol SecretSignedPreKeyProtocol: AnyObject, Sendable {
    
    func publicForm()  -> SignedPreKeyPublic
    
    func serialize()  -> Data
    
}
open class SecretSignedPreKey: SecretSignedPreKeyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_chencang_bindings_fn_clone_secretsignedprekey(self.handle, $0) }
    }
public convenience init(ik: SecretIdentity, spkVersion: UInt32)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_secretsignedprekey_new(
        FfiConverterTypeSecretIdentity_lower(ik),
        FfiConverterUInt32.lower(spkVersion),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_chencang_bindings_fn_free_secretsignedprekey(handle, $0) }
    }

    
public static func fromSerialized(data: Data)throws  -> SecretSignedPreKey  {
    return try  FfiConverterTypeSecretSignedPreKey_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_secretsignedprekey_from_serialized(
        FfiConverterData.lower(data),$0
    )
})
}
    

    
open func publicForm() -> SignedPreKeyPublic  {
    return try!  FfiConverterTypeSignedPreKeyPublic_lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_secretsignedprekey_public_form(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func serialize() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_secretsignedprekey_serialize(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretSignedPreKey: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SecretSignedPreKey

    public static func lift(_ handle: UInt64) throws -> SecretSignedPreKey {
        return SecretSignedPreKey(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SecretSignedPreKey) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretSignedPreKey {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SecretSignedPreKey, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretSignedPreKey_lift(_ handle: UInt64) throws -> SecretSignedPreKey {
    return try FfiConverterTypeSecretSignedPreKey.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretSignedPreKey_lower(_ value: SecretSignedPreKey) -> UInt64 {
    return FfiConverterTypeSecretSignedPreKey.lower(value)
}






public protocol SessionProtocol: AnyObject, Sendable {
    
    func decrypt(wireText: String) throws  -> Data
    
    func decryptFromBytes(ciphertext: Data) throws  -> Data
    
    func encrypt(plaintext: Data) throws  -> String
    
    func encryptToBytes(plaintext: Data) throws  -> Data
    
    func serializeState()  -> Data
    
}
open class Session: SessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_chencang_bindings_fn_clone_session(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_chencang_bindings_fn_free_session(handle, $0) }
    }

    
public static func fromSerializedState(state: Data)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_session_from_serialized_state(
        FfiConverterData.lower(state),$0
    )
})
}
    
public static func initiatorAfterHandshake(sessionRootKey: Data, sessionId: Data, aliceIkPublic: PublicIdentity, ekX25519Secret: Data, ekMlkemSecret: Data)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_session_initiator_after_handshake(
        FfiConverterData.lower(sessionRootKey),
        FfiConverterData.lower(sessionId),
        FfiConverterTypePublicIdentity_lower(aliceIkPublic),
        FfiConverterData.lower(ekX25519Secret),
        FfiConverterData.lower(ekMlkemSecret),$0
    )
})
}
    
public static func initiatorAfterHandshakeClassical(sessionRootKey: Data, sessionId: Data, aliceIkDhX25519: Data, ekX25519Secret: Data)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_session_initiator_after_handshake_classical(
        FfiConverterData.lower(sessionRootKey),
        FfiConverterData.lower(sessionId),
        FfiConverterData.lower(aliceIkDhX25519),
        FfiConverterData.lower(ekX25519Secret),$0
    )
})
}
    
public static func responderAfterHandshake(sessionRootKey: Data, sessionId: Data, initiatorOutput: InitiatorHandshakeOutput)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_session_responder_after_handshake(
        FfiConverterData.lower(sessionRootKey),
        FfiConverterData.lower(sessionId),
        FfiConverterTypeInitiatorHandshakeOutput_lower(initiatorOutput),$0
    )
})
}
    
public static func responderAfterHandshakeClassical(sessionRootKey: Data, sessionId: Data, bobEkX25519Pub: Data)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_constructor_session_responder_after_handshake_classical(
        FfiConverterData.lower(sessionRootKey),
        FfiConverterData.lower(sessionId),
        FfiConverterData.lower(bobEkX25519Pub),$0
    )
})
}
    

    
open func decrypt(wireText: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_method_session_decrypt(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(wireText),$0
    )
})
}
    
open func decryptFromBytes(ciphertext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_method_session_decrypt_from_bytes(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    
open func encrypt(plaintext: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_method_session_encrypt(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
open func encryptToBytes(plaintext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_method_session_encrypt_to_bytes(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
open func serializeState() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_method_session_serialize_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Session

    public static func lift(_ handle: UInt64) throws -> Session {
        return Session(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Session) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Session {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Session, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lift(_ handle: UInt64) throws -> Session {
    return try FfiConverterTypeSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lower(_ value: Session) -> UInt64 {
    return FfiConverterTypeSession.lower(value)
}




public struct BlobMaterial: Equatable, Hashable {
    public var blobId: Data
    public var blobKey: Data
    public var blobNonce: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blobId: Data, blobKey: Data, blobNonce: Data) {
        self.blobId = blobId
        self.blobKey = blobKey
        self.blobNonce = blobNonce
    }

    

    
}

#if compiler(>=6)
extension BlobMaterial: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBlobMaterial: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BlobMaterial {
        return
            try BlobMaterial(
                blobId: FfiConverterData.read(from: &buf), 
                blobKey: FfiConverterData.read(from: &buf), 
                blobNonce: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: BlobMaterial, into buf: inout [UInt8]) {
        FfiConverterData.write(value.blobId, into: &buf)
        FfiConverterData.write(value.blobKey, into: &buf)
        FfiConverterData.write(value.blobNonce, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlobMaterial_lift(_ buf: RustBuffer) throws -> BlobMaterial {
    return try FfiConverterTypeBlobMaterial.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlobMaterial_lower(_ value: BlobMaterial) -> RustBuffer {
    return FfiConverterTypeBlobMaterial.lower(value)
}


public struct ClassicalInbandHeader: Equatable, Hashable {
    public var version: UInt8
    public var suiteId: UInt8
    public var bobIk: ClassicalPublicIdentity
    public var ekX25519Pub: Data
    public var sessionId: Data
    public var confirmB: Data
    public var bobDisplayName: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(version: UInt8, suiteId: UInt8, bobIk: ClassicalPublicIdentity, ekX25519Pub: Data, sessionId: Data, confirmB: Data, bobDisplayName: String?) {
        self.version = version
        self.suiteId = suiteId
        self.bobIk = bobIk
        self.ekX25519Pub = ekX25519Pub
        self.sessionId = sessionId
        self.confirmB = confirmB
        self.bobDisplayName = bobDisplayName
    }

    

    
}

#if compiler(>=6)
extension ClassicalInbandHeader: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalInbandHeader: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalInbandHeader {
        return
            try ClassicalInbandHeader(
                version: FfiConverterUInt8.read(from: &buf), 
                suiteId: FfiConverterUInt8.read(from: &buf), 
                bobIk: FfiConverterTypeClassicalPublicIdentity.read(from: &buf), 
                ekX25519Pub: FfiConverterData.read(from: &buf), 
                sessionId: FfiConverterData.read(from: &buf), 
                confirmB: FfiConverterData.read(from: &buf), 
                bobDisplayName: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalInbandHeader, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.version, into: &buf)
        FfiConverterUInt8.write(value.suiteId, into: &buf)
        FfiConverterTypeClassicalPublicIdentity.write(value.bobIk, into: &buf)
        FfiConverterData.write(value.ekX25519Pub, into: &buf)
        FfiConverterData.write(value.sessionId, into: &buf)
        FfiConverterData.write(value.confirmB, into: &buf)
        FfiConverterOptionString.write(value.bobDisplayName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalInbandHeader_lift(_ buf: RustBuffer) throws -> ClassicalInbandHeader {
    return try FfiConverterTypeClassicalInbandHeader.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalInbandHeader_lower(_ value: ClassicalInbandHeader) -> RustBuffer {
    return FfiConverterTypeClassicalInbandHeader.lower(value)
}


public struct ClassicalInitiatorOutput: Equatable, Hashable {
    public var sessionRootKey: Data
    public var bobIk: PublicIdentity
    public var ekX25519Pub: Data
    public var ekX25519Secret: Data
    public var transcript: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionRootKey: Data, bobIk: PublicIdentity, ekX25519Pub: Data, ekX25519Secret: Data, transcript: Data) {
        self.sessionRootKey = sessionRootKey
        self.bobIk = bobIk
        self.ekX25519Pub = ekX25519Pub
        self.ekX25519Secret = ekX25519Secret
        self.transcript = transcript
    }

    

    
}

#if compiler(>=6)
extension ClassicalInitiatorOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalInitiatorOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalInitiatorOutput {
        return
            try ClassicalInitiatorOutput(
                sessionRootKey: FfiConverterData.read(from: &buf), 
                bobIk: FfiConverterTypePublicIdentity.read(from: &buf), 
                ekX25519Pub: FfiConverterData.read(from: &buf), 
                ekX25519Secret: FfiConverterData.read(from: &buf), 
                transcript: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalInitiatorOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sessionRootKey, into: &buf)
        FfiConverterTypePublicIdentity.write(value.bobIk, into: &buf)
        FfiConverterData.write(value.ekX25519Pub, into: &buf)
        FfiConverterData.write(value.ekX25519Secret, into: &buf)
        FfiConverterData.write(value.transcript, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalInitiatorOutput_lift(_ buf: RustBuffer) throws -> ClassicalInitiatorOutput {
    return try FfiConverterTypeClassicalInitiatorOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalInitiatorOutput_lower(_ value: ClassicalInitiatorOutput) -> RustBuffer {
    return FfiConverterTypeClassicalInitiatorOutput.lower(value)
}


public struct ClassicalOneTimePreKey: Equatable, Hashable {
    public var id: UInt32
    public var x25519: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt32, x25519: Data) {
        self.id = id
        self.x25519 = x25519
    }

    

    
}

#if compiler(>=6)
extension ClassicalOneTimePreKey: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalOneTimePreKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalOneTimePreKey {
        return
            try ClassicalOneTimePreKey(
                id: FfiConverterUInt32.read(from: &buf), 
                x25519: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalOneTimePreKey, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.id, into: &buf)
        FfiConverterData.write(value.x25519, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalOneTimePreKey_lift(_ buf: RustBuffer) throws -> ClassicalOneTimePreKey {
    return try FfiConverterTypeClassicalOneTimePreKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalOneTimePreKey_lower(_ value: ClassicalOneTimePreKey) -> RustBuffer {
    return FfiConverterTypeClassicalOneTimePreKey.lower(value)
}


public struct ClassicalPreKeyBundle: Equatable, Hashable {
    public var version: UInt8
    public var suiteId: UInt8
    public var ik: ClassicalPublicIdentity
    public var spk: ClassicalSignedPreKey
    public var opk: ClassicalOneTimePreKey?
    public var pairingNonce: Data
    public var inviterUsername: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(version: UInt8, suiteId: UInt8, ik: ClassicalPublicIdentity, spk: ClassicalSignedPreKey, opk: ClassicalOneTimePreKey?, pairingNonce: Data, inviterUsername: String) {
        self.version = version
        self.suiteId = suiteId
        self.ik = ik
        self.spk = spk
        self.opk = opk
        self.pairingNonce = pairingNonce
        self.inviterUsername = inviterUsername
    }

    

    
}

#if compiler(>=6)
extension ClassicalPreKeyBundle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalPreKeyBundle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalPreKeyBundle {
        return
            try ClassicalPreKeyBundle(
                version: FfiConverterUInt8.read(from: &buf), 
                suiteId: FfiConverterUInt8.read(from: &buf), 
                ik: FfiConverterTypeClassicalPublicIdentity.read(from: &buf), 
                spk: FfiConverterTypeClassicalSignedPreKey.read(from: &buf), 
                opk: FfiConverterOptionTypeClassicalOneTimePreKey.read(from: &buf), 
                pairingNonce: FfiConverterData.read(from: &buf), 
                inviterUsername: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalPreKeyBundle, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.version, into: &buf)
        FfiConverterUInt8.write(value.suiteId, into: &buf)
        FfiConverterTypeClassicalPublicIdentity.write(value.ik, into: &buf)
        FfiConverterTypeClassicalSignedPreKey.write(value.spk, into: &buf)
        FfiConverterOptionTypeClassicalOneTimePreKey.write(value.opk, into: &buf)
        FfiConverterData.write(value.pairingNonce, into: &buf)
        FfiConverterString.write(value.inviterUsername, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalPreKeyBundle_lift(_ buf: RustBuffer) throws -> ClassicalPreKeyBundle {
    return try FfiConverterTypeClassicalPreKeyBundle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalPreKeyBundle_lower(_ value: ClassicalPreKeyBundle) -> RustBuffer {
    return FfiConverterTypeClassicalPreKeyBundle.lower(value)
}


public struct ClassicalPublicIdentity: Equatable, Hashable {
    public var ed25519: Data
    public var x25519: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ed25519: Data, x25519: Data) {
        self.ed25519 = ed25519
        self.x25519 = x25519
    }

    

    
}

#if compiler(>=6)
extension ClassicalPublicIdentity: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalPublicIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalPublicIdentity {
        return
            try ClassicalPublicIdentity(
                ed25519: FfiConverterData.read(from: &buf), 
                x25519: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalPublicIdentity, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ed25519, into: &buf)
        FfiConverterData.write(value.x25519, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalPublicIdentity_lift(_ buf: RustBuffer) throws -> ClassicalPublicIdentity {
    return try FfiConverterTypeClassicalPublicIdentity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalPublicIdentity_lower(_ value: ClassicalPublicIdentity) -> RustBuffer {
    return FfiConverterTypeClassicalPublicIdentity.lower(value)
}


public struct ClassicalResponderOutput: Equatable, Hashable {
    public var sessionRootKey: Data
    public var transcript: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionRootKey: Data, transcript: Data) {
        self.sessionRootKey = sessionRootKey
        self.transcript = transcript
    }

    

    
}

#if compiler(>=6)
extension ClassicalResponderOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalResponderOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalResponderOutput {
        return
            try ClassicalResponderOutput(
                sessionRootKey: FfiConverterData.read(from: &buf), 
                transcript: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalResponderOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sessionRootKey, into: &buf)
        FfiConverterData.write(value.transcript, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalResponderOutput_lift(_ buf: RustBuffer) throws -> ClassicalResponderOutput {
    return try FfiConverterTypeClassicalResponderOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalResponderOutput_lower(_ value: ClassicalResponderOutput) -> RustBuffer {
    return FfiConverterTypeClassicalResponderOutput.lower(value)
}


public struct ClassicalSignedPreKey: Equatable, Hashable {
    public var x25519: Data
    public var sigEd25519: Data
    public var epoch: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x25519: Data, sigEd25519: Data, epoch: UInt32) {
        self.x25519 = x25519
        self.sigEd25519 = sigEd25519
        self.epoch = epoch
    }

    

    
}

#if compiler(>=6)
extension ClassicalSignedPreKey: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClassicalSignedPreKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClassicalSignedPreKey {
        return
            try ClassicalSignedPreKey(
                x25519: FfiConverterData.read(from: &buf), 
                sigEd25519: FfiConverterData.read(from: &buf), 
                epoch: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ClassicalSignedPreKey, into buf: inout [UInt8]) {
        FfiConverterData.write(value.x25519, into: &buf)
        FfiConverterData.write(value.sigEd25519, into: &buf)
        FfiConverterUInt32.write(value.epoch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalSignedPreKey_lift(_ buf: RustBuffer) throws -> ClassicalSignedPreKey {
    return try FfiConverterTypeClassicalSignedPreKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClassicalSignedPreKey_lower(_ value: ClassicalSignedPreKey) -> RustBuffer {
    return FfiConverterTypeClassicalSignedPreKey.lower(value)
}


public struct Fingerprint: Equatable, Hashable {
    public var value: Data
    public var hex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(value: Data, hex: String) {
        self.value = value
        self.hex = hex
    }

    

    
}

#if compiler(>=6)
extension Fingerprint: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFingerprint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Fingerprint {
        return
            try Fingerprint(
                value: FfiConverterData.read(from: &buf), 
                hex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Fingerprint, into buf: inout [UInt8]) {
        FfiConverterData.write(value.value, into: &buf)
        FfiConverterString.write(value.hex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFingerprint_lift(_ buf: RustBuffer) throws -> Fingerprint {
    return try FfiConverterTypeFingerprint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFingerprint_lower(_ value: Fingerprint) -> RustBuffer {
    return FfiConverterTypeFingerprint.lower(value)
}


public struct InitiatorHandshakeOutput: Equatable, Hashable {
    public var sessionRootKey: Data
    public var bobIdentityPublic: PublicIdentity
    public var ekX25519Pub: Data
    public var ekMlkemPub: Data
    public var kemCtToSpk: Data
    public var kemCtToIk: Data
    public var kemCtToOpk: Data?
    public var ekX25519Secret: Data?
    public var ekMlkemSecret: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sessionRootKey: Data, bobIdentityPublic: PublicIdentity, ekX25519Pub: Data, ekMlkemPub: Data, kemCtToSpk: Data, kemCtToIk: Data, kemCtToOpk: Data?, ekX25519Secret: Data?, ekMlkemSecret: Data?) {
        self.sessionRootKey = sessionRootKey
        self.bobIdentityPublic = bobIdentityPublic
        self.ekX25519Pub = ekX25519Pub
        self.ekMlkemPub = ekMlkemPub
        self.kemCtToSpk = kemCtToSpk
        self.kemCtToIk = kemCtToIk
        self.kemCtToOpk = kemCtToOpk
        self.ekX25519Secret = ekX25519Secret
        self.ekMlkemSecret = ekMlkemSecret
    }

    

    
}

#if compiler(>=6)
extension InitiatorHandshakeOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInitiatorHandshakeOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InitiatorHandshakeOutput {
        return
            try InitiatorHandshakeOutput(
                sessionRootKey: FfiConverterData.read(from: &buf), 
                bobIdentityPublic: FfiConverterTypePublicIdentity.read(from: &buf), 
                ekX25519Pub: FfiConverterData.read(from: &buf), 
                ekMlkemPub: FfiConverterData.read(from: &buf), 
                kemCtToSpk: FfiConverterData.read(from: &buf), 
                kemCtToIk: FfiConverterData.read(from: &buf), 
                kemCtToOpk: FfiConverterOptionData.read(from: &buf), 
                ekX25519Secret: FfiConverterOptionData.read(from: &buf), 
                ekMlkemSecret: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: InitiatorHandshakeOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.sessionRootKey, into: &buf)
        FfiConverterTypePublicIdentity.write(value.bobIdentityPublic, into: &buf)
        FfiConverterData.write(value.ekX25519Pub, into: &buf)
        FfiConverterData.write(value.ekMlkemPub, into: &buf)
        FfiConverterData.write(value.kemCtToSpk, into: &buf)
        FfiConverterData.write(value.kemCtToIk, into: &buf)
        FfiConverterOptionData.write(value.kemCtToOpk, into: &buf)
        FfiConverterOptionData.write(value.ekX25519Secret, into: &buf)
        FfiConverterOptionData.write(value.ekMlkemSecret, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInitiatorHandshakeOutput_lift(_ buf: RustBuffer) throws -> InitiatorHandshakeOutput {
    return try FfiConverterTypeInitiatorHandshakeOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInitiatorHandshakeOutput_lower(_ value: InitiatorHandshakeOutput) -> RustBuffer {
    return FfiConverterTypeInitiatorHandshakeOutput.lower(value)
}


public struct MediaBlob: Equatable, Hashable {
    public var blobSecret: Data
    public var blob: Data
    public var blobId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blobSecret: Data, blob: Data, blobId: String) {
        self.blobSecret = blobSecret
        self.blob = blob
        self.blobId = blobId
    }

    

    
}

#if compiler(>=6)
extension MediaBlob: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMediaBlob: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MediaBlob {
        return
            try MediaBlob(
                blobSecret: FfiConverterData.read(from: &buf), 
                blob: FfiConverterData.read(from: &buf), 
                blobId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MediaBlob, into buf: inout [UInt8]) {
        FfiConverterData.write(value.blobSecret, into: &buf)
        FfiConverterData.write(value.blob, into: &buf)
        FfiConverterString.write(value.blobId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaBlob_lift(_ buf: RustBuffer) throws -> MediaBlob {
    return try FfiConverterTypeMediaBlob.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaBlob_lower(_ value: MediaBlob) -> RustBuffer {
    return FfiConverterTypeMediaBlob.lower(value)
}


public struct MediaRef: Equatable, Hashable {
    public var kind: UInt8
    public var durMs: UInt16
    public var width: UInt16
    public var height: UInt16
    public var byteLen: UInt32
    public var blobSecret: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: UInt8, durMs: UInt16, width: UInt16, height: UInt16, byteLen: UInt32, blobSecret: Data) {
        self.kind = kind
        self.durMs = durMs
        self.width = width
        self.height = height
        self.byteLen = byteLen
        self.blobSecret = blobSecret
    }

    

    
}

#if compiler(>=6)
extension MediaRef: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMediaRef: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MediaRef {
        return
            try MediaRef(
                kind: FfiConverterUInt8.read(from: &buf), 
                durMs: FfiConverterUInt16.read(from: &buf), 
                width: FfiConverterUInt16.read(from: &buf), 
                height: FfiConverterUInt16.read(from: &buf), 
                byteLen: FfiConverterUInt32.read(from: &buf), 
                blobSecret: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MediaRef, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.kind, into: &buf)
        FfiConverterUInt16.write(value.durMs, into: &buf)
        FfiConverterUInt16.write(value.width, into: &buf)
        FfiConverterUInt16.write(value.height, into: &buf)
        FfiConverterUInt32.write(value.byteLen, into: &buf)
        FfiConverterData.write(value.blobSecret, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaRef_lift(_ buf: RustBuffer) throws -> MediaRef {
    return try FfiConverterTypeMediaRef.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaRef_lower(_ value: MediaRef) -> RustBuffer {
    return FfiConverterTypeMediaRef.lower(value)
}


public struct OneTimePreKeyPublic: Equatable, Hashable {
    public var opkIndex: UInt32
    public var opkX25519: Data
    public var opkMlkem768: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(opkIndex: UInt32, opkX25519: Data, opkMlkem768: Data) {
        self.opkIndex = opkIndex
        self.opkX25519 = opkX25519
        self.opkMlkem768 = opkMlkem768
    }

    

    
}

#if compiler(>=6)
extension OneTimePreKeyPublic: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOneTimePreKeyPublic: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OneTimePreKeyPublic {
        return
            try OneTimePreKeyPublic(
                opkIndex: FfiConverterUInt32.read(from: &buf), 
                opkX25519: FfiConverterData.read(from: &buf), 
                opkMlkem768: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: OneTimePreKeyPublic, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.opkIndex, into: &buf)
        FfiConverterData.write(value.opkX25519, into: &buf)
        FfiConverterData.write(value.opkMlkem768, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOneTimePreKeyPublic_lift(_ buf: RustBuffer) throws -> OneTimePreKeyPublic {
    return try FfiConverterTypeOneTimePreKeyPublic.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOneTimePreKeyPublic_lower(_ value: OneTimePreKeyPublic) -> RustBuffer {
    return FfiConverterTypeOneTimePreKeyPublic.lower(value)
}


public struct PreKeyBundle: Equatable, Hashable {
    public var ik: PublicIdentity
    public var spk: SignedPreKeyPublic
    public var opk: OneTimePreKeyPublic?
    public var inviterUsername: String
    public var inviteId: Data
    public var pairingNonce: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ik: PublicIdentity, spk: SignedPreKeyPublic, opk: OneTimePreKeyPublic?, inviterUsername: String, inviteId: Data, pairingNonce: Data) {
        self.ik = ik
        self.spk = spk
        self.opk = opk
        self.inviterUsername = inviterUsername
        self.inviteId = inviteId
        self.pairingNonce = pairingNonce
    }

    

    
}

#if compiler(>=6)
extension PreKeyBundle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreKeyBundle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreKeyBundle {
        return
            try PreKeyBundle(
                ik: FfiConverterTypePublicIdentity.read(from: &buf), 
                spk: FfiConverterTypeSignedPreKeyPublic.read(from: &buf), 
                opk: FfiConverterOptionTypeOneTimePreKeyPublic.read(from: &buf), 
                inviterUsername: FfiConverterString.read(from: &buf), 
                inviteId: FfiConverterData.read(from: &buf), 
                pairingNonce: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: PreKeyBundle, into buf: inout [UInt8]) {
        FfiConverterTypePublicIdentity.write(value.ik, into: &buf)
        FfiConverterTypeSignedPreKeyPublic.write(value.spk, into: &buf)
        FfiConverterOptionTypeOneTimePreKeyPublic.write(value.opk, into: &buf)
        FfiConverterString.write(value.inviterUsername, into: &buf)
        FfiConverterData.write(value.inviteId, into: &buf)
        FfiConverterData.write(value.pairingNonce, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreKeyBundle_lift(_ buf: RustBuffer) throws -> PreKeyBundle {
    return try FfiConverterTypePreKeyBundle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreKeyBundle_lower(_ value: PreKeyBundle) -> RustBuffer {
    return FfiConverterTypePreKeyBundle.lower(value)
}


public struct PublicIdentity: Equatable, Hashable {
    public var ikDhX25519: Data
    public var ikSigEd25519: Data
    public var ikKemMlkem768: Data
    public var ikSigMldsa65: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ikDhX25519: Data, ikSigEd25519: Data, ikKemMlkem768: Data, ikSigMldsa65: Data) {
        self.ikDhX25519 = ikDhX25519
        self.ikSigEd25519 = ikSigEd25519
        self.ikKemMlkem768 = ikKemMlkem768
        self.ikSigMldsa65 = ikSigMldsa65
    }

    

    
}

#if compiler(>=6)
extension PublicIdentity: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePublicIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PublicIdentity {
        return
            try PublicIdentity(
                ikDhX25519: FfiConverterData.read(from: &buf), 
                ikSigEd25519: FfiConverterData.read(from: &buf), 
                ikKemMlkem768: FfiConverterData.read(from: &buf), 
                ikSigMldsa65: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: PublicIdentity, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ikDhX25519, into: &buf)
        FfiConverterData.write(value.ikSigEd25519, into: &buf)
        FfiConverterData.write(value.ikKemMlkem768, into: &buf)
        FfiConverterData.write(value.ikSigMldsa65, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublicIdentity_lift(_ buf: RustBuffer) throws -> PublicIdentity {
    return try FfiConverterTypePublicIdentity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublicIdentity_lower(_ value: PublicIdentity) -> RustBuffer {
    return FfiConverterTypePublicIdentity.lower(value)
}


public struct SignedPreKeyPublic: Equatable, Hashable {
    public var spkVersion: UInt32
    public var spkX25519: Data
    public var spkMlkem768: Data
    public var ed25519Sig: Data
    public var ed25519SigClassical: Data
    public var mldsa65Sig: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(spkVersion: UInt32, spkX25519: Data, spkMlkem768: Data, ed25519Sig: Data, ed25519SigClassical: Data, mldsa65Sig: Data) {
        self.spkVersion = spkVersion
        self.spkX25519 = spkX25519
        self.spkMlkem768 = spkMlkem768
        self.ed25519Sig = ed25519Sig
        self.ed25519SigClassical = ed25519SigClassical
        self.mldsa65Sig = mldsa65Sig
    }

    

    
}

#if compiler(>=6)
extension SignedPreKeyPublic: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignedPreKeyPublic: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignedPreKeyPublic {
        return
            try SignedPreKeyPublic(
                spkVersion: FfiConverterUInt32.read(from: &buf), 
                spkX25519: FfiConverterData.read(from: &buf), 
                spkMlkem768: FfiConverterData.read(from: &buf), 
                ed25519Sig: FfiConverterData.read(from: &buf), 
                ed25519SigClassical: FfiConverterData.read(from: &buf), 
                mldsa65Sig: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SignedPreKeyPublic, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.spkVersion, into: &buf)
        FfiConverterData.write(value.spkX25519, into: &buf)
        FfiConverterData.write(value.spkMlkem768, into: &buf)
        FfiConverterData.write(value.ed25519Sig, into: &buf)
        FfiConverterData.write(value.ed25519SigClassical, into: &buf)
        FfiConverterData.write(value.mldsa65Sig, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignedPreKeyPublic_lift(_ buf: RustBuffer) throws -> SignedPreKeyPublic {
    return try FfiConverterTypeSignedPreKeyPublic.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignedPreKeyPublic_lower(_ value: SignedPreKeyPublic) -> RustBuffer {
    return FfiConverterTypeSignedPreKeyPublic.lower(value)
}


public enum ChencangError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidLength(message: String)
    
    case UnsupportedSuite(message: String)
    
    case UnsupportedVersion(message: String)
    
    case AeadFailed(message: String)
    
    case SignatureFailed(message: String)
    
    case Decoding(message: String)
    
    case Internal(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ChencangError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChencangError: FfiConverterRustBuffer {
    typealias SwiftType = ChencangError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChencangError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidLength(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .UnsupportedSuite(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .UnsupportedVersion(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .AeadFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .SignatureFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Decoding(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .Internal(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChencangError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidLength(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .UnsupportedSuite(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .UnsupportedVersion(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .AeadFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .SignatureFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Decoding(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .Internal(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChencangError_lift(_ buf: RustBuffer) throws -> ChencangError {
    return try FfiConverterTypeChencangError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChencangError_lower(_ value: ChencangError) -> RustBuffer {
    return FfiConverterTypeChencangError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DecodedMessage: Equatable, Hashable {
    
    case text(value: String
    )
    case media(refs: [MediaRef]
    )





}

#if compiler(>=6)
extension DecodedMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecodedMessage: FfiConverterRustBuffer {
    typealias SwiftType = DecodedMessage

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecodedMessage {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text(value: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .media(refs: try FfiConverterSequenceTypeMediaRef.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DecodedMessage, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .text(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        
        case let .media(refs):
            writeInt(&buf, Int32(2))
            FfiConverterSequenceTypeMediaRef.write(refs, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodedMessage_lift(_ buf: RustBuffer) throws -> DecodedMessage {
    return try FfiConverterTypeDecodedMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodedMessage_lower(_ value: DecodedMessage) -> RustBuffer {
    return FfiConverterTypeDecodedMessage.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSecretOneTimePreKey: FfiConverterRustBuffer {
    typealias SwiftType = SecretOneTimePreKey?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSecretOneTimePreKey.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSecretOneTimePreKey.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeClassicalOneTimePreKey: FfiConverterRustBuffer {
    typealias SwiftType = ClassicalOneTimePreKey?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeClassicalOneTimePreKey.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeClassicalOneTimePreKey.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeOneTimePreKeyPublic: FfiConverterRustBuffer {
    typealias SwiftType = OneTimePreKeyPublic?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeOneTimePreKeyPublic.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeOneTimePreKeyPublic.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMediaRef: FfiConverterRustBuffer {
    typealias SwiftType = [MediaRef]

    public static func write(_ value: [MediaRef], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMediaRef.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MediaRef] {
        let len: Int32 = try readInt(&buf)
        var seq = [MediaRef]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMediaRef.read(from: &buf))
        }
        return seq
    }
}
public func computeConfirmTag(srk: Data, transcript: Data, who: UInt8)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_compute_confirm_tag(
        FfiConverterData.lower(srk),
        FfiConverterData.lower(transcript),
        FfiConverterUInt8.lower(who),$0
    )
})
}
public func confirmWhoInitiator() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_confirm_who_initiator($0
    )
})
}
public func confirmWhoResponder() -> UInt8  {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_confirm_who_responder($0
    )
})
}
public func decodeClassicalBundle(bytes: Data)throws  -> ClassicalPreKeyBundle  {
    return try  FfiConverterTypeClassicalPreKeyBundle_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_decode_classical_bundle(
        FfiConverterData.lower(bytes),$0
    )
})
}
public func decodeClassicalHeader(bytes: Data)throws  -> ClassicalInbandHeader  {
    return try  FfiConverterTypeClassicalInbandHeader_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_decode_classical_header(
        FfiConverterData.lower(bytes),$0
    )
})
}
public func decodeFrame(bytes: Data)throws  -> DecodedMessage  {
    return try  FfiConverterTypeDecodedMessage_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_decode_frame(
        FfiConverterData.lower(bytes),$0
    )
})
}
public func decodeWire(s: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_decode_wire(
        FfiConverterString.lower(s),$0
    )
})
}
public func decryptMediaBlob(blob: Data, blobSecret: Data, expectedKind: UInt8)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_decrypt_media_blob(
        FfiConverterData.lower(blob),
        FfiConverterData.lower(blobSecret),
        FfiConverterUInt8.lower(expectedKind),$0
    )
})
}
public func deriveBlobMaterial(blobSecret: Data)throws  -> BlobMaterial  {
    return try  FfiConverterTypeBlobMaterial_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_derive_blob_material(
        FfiConverterData.lower(blobSecret),$0
    )
})
}
public func deriveInitiatorClassical(bobIk: SecretIdentity, aliceBundle: ClassicalPreKeyBundle)throws  -> ClassicalInitiatorOutput  {
    return try  FfiConverterTypeClassicalInitiatorOutput_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_derive_initiator_classical(
        FfiConverterTypeSecretIdentity_lower(bobIk),
        FfiConverterTypeClassicalPreKeyBundle_lower(aliceBundle),$0
    )
})
}
public func deriveInitiatorHandshake(bobIk: SecretIdentity, aliceBundle: PreKeyBundle)throws  -> InitiatorHandshakeOutput  {
    return try  FfiConverterTypeInitiatorHandshakeOutput_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_derive_initiator_handshake(
        FfiConverterTypeSecretIdentity_lower(bobIk),
        FfiConverterTypePreKeyBundle_lower(aliceBundle),$0
    )
})
}
public func deriveResponderClassical(aliceIk: SecretIdentity, aliceSpk: SecretSignedPreKey, aliceOpk: SecretOneTimePreKey?, bobIk: ClassicalPublicIdentity, bobEkX25519Pub: Data, opkId: UInt32?, pairingNonce: Data)throws  -> ClassicalResponderOutput  {
    return try  FfiConverterTypeClassicalResponderOutput_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_derive_responder_classical(
        FfiConverterTypeSecretIdentity_lower(aliceIk),
        FfiConverterTypeSecretSignedPreKey_lower(aliceSpk),
        FfiConverterOptionTypeSecretOneTimePreKey.lower(aliceOpk),
        FfiConverterTypeClassicalPublicIdentity_lower(bobIk),
        FfiConverterData.lower(bobEkX25519Pub),
        FfiConverterOptionUInt32.lower(opkId),
        FfiConverterData.lower(pairingNonce),$0
    )
})
}
public func deriveResponderHandshake(aliceIk: SecretIdentity, aliceSpk: SecretSignedPreKey, aliceOpk: SecretOneTimePreKey?, bobIkPub: PublicIdentity, bobEkXPub: Data, bobEkKemPub: Data, kemCtToSpk: Data, kemCtToIk: Data, kemCtToOpk: Data?, pairingNonce: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_derive_responder_handshake(
        FfiConverterTypeSecretIdentity_lower(aliceIk),
        FfiConverterTypeSecretSignedPreKey_lower(aliceSpk),
        FfiConverterOptionTypeSecretOneTimePreKey.lower(aliceOpk),
        FfiConverterTypePublicIdentity_lower(bobIkPub),
        FfiConverterData.lower(bobEkXPub),
        FfiConverterData.lower(bobEkKemPub),
        FfiConverterData.lower(kemCtToSpk),
        FfiConverterData.lower(kemCtToIk),
        FfiConverterOptionData.lower(kemCtToOpk),
        FfiConverterData.lower(pairingNonce),$0
    )
})
}
public func deriveSafetyEmoji(sessionSecret: Data)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_derive_safety_emoji(
        FfiConverterData.lower(sessionSecret),$0
    )
})
}
public func encodeClassicalBundle(bundle: ClassicalPreKeyBundle)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_encode_classical_bundle(
        FfiConverterTypeClassicalPreKeyBundle_lower(bundle),$0
    )
})
}
public func encodeClassicalHeader(header: ClassicalInbandHeader)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_encode_classical_header(
        FfiConverterTypeClassicalInbandHeader_lower(header),$0
    )
})
}
public func encodeMediaRefFrame(refs: [MediaRef])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_encode_media_ref_frame(
        FfiConverterSequenceTypeMediaRef.lower(refs),$0
    )
})
}
public func encodeTextFrame(text: String) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_encode_text_frame(
        FfiConverterString.lower(text),$0
    )
})
}
public func encodeWire(ciphertext: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_encode_wire(
        FfiConverterData.lower(ciphertext),$0
    )
})
}
public func encryptMediaBlob(plaintext: Data, kind: UInt8)throws  -> MediaBlob  {
    return try  FfiConverterTypeMediaBlob_lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_encrypt_media_blob(
        FfiConverterData.lower(plaintext),
        FfiConverterUInt8.lower(kind),$0
    )
})
}
public func fingerprintOfPublic(identity: PublicIdentity) -> Fingerprint  {
    return try!  FfiConverterTypeFingerprint_lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_fingerprint_of_public(
        FfiConverterTypePublicIdentity_lower(identity),$0
    )
})
}
public func generateSecretIdentity() -> SecretIdentity  {
    return try!  FfiConverterTypeSecretIdentity_lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_generate_secret_identity($0
    )
})
}
public func mediaBlobId(blobSecret: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_media_blob_id(
        FfiConverterData.lower(blobSecret),$0
    )
})
}
public func verifyConfirmTag(srk: Data, transcript: Data, who: UInt8, tag: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeChencangError_lift) {
    uniffi_chencang_bindings_fn_func_verify_confirm_tag(
        FfiConverterData.lower(srk),
        FfiConverterData.lower(transcript),
        FfiConverterUInt8.lower(who),
        FfiConverterData.lower(tag),$0
    )
})
}
public func verifySignedConfig(payload: Data, sig: Data) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_chencang_bindings_fn_func_verify_signed_config(
        FfiConverterData.lower(payload),
        FfiConverterData.lower(sig),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_chencang_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_compute_confirm_tag() != 44369) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_confirm_who_initiator() != 8294) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_confirm_who_responder() != 53413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_decode_classical_bundle() != 2550) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_decode_classical_header() != 30056) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_decode_frame() != 24453) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_decode_wire() != 48312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_decrypt_media_blob() != 46259) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_derive_blob_material() != 52796) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_derive_initiator_classical() != 49341) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_derive_initiator_handshake() != 23221) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_derive_responder_classical() != 42030) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_derive_responder_handshake() != 27882) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_derive_safety_emoji() != 51584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_encode_classical_bundle() != 61156) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_encode_classical_header() != 40210) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_encode_media_ref_frame() != 36977) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_encode_text_frame() != 4257) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_encode_wire() != 61257) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_encrypt_media_blob() != 40382) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_fingerprint_of_public() != 55994) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_generate_secret_identity() != 44170) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_media_blob_id() != 9243) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_verify_confirm_tag() != 48166) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_func_verify_signed_config() != 11681) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_secretidentity_public_identity() != 4862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_secretidentity_serialize_for_local_storage() != 54169) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_secretidentity_sign_ed25519_ik() != 3412) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_secretonetimeprekey_public_form() != 50743) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_secretsignedprekey_public_form() != 1889) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_secretsignedprekey_serialize() != 35237) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_session_decrypt() != 16621) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_session_decrypt_from_bytes() != 40862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_session_encrypt() != 28508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_session_encrypt_to_bytes() != 27856) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_method_session_serialize_state() != 18378) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_secretidentity_from_local_storage() != 13111) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_secretidentity_new() != 22081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_secretonetimeprekey_new() != 40865) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_secretsignedprekey_from_serialized() != 56437) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_secretsignedprekey_new() != 4900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_session_from_serialized_state() != 40791) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_session_initiator_after_handshake() != 42634) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_session_initiator_after_handshake_classical() != 27721) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_session_responder_after_handshake() != 29343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chencang_bindings_checksum_constructor_session_responder_after_handshake_classical() != 37586) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureChencangBindingsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all