// swift-tools-version: 5.9
import PackageDescription

// SwiftPM package for the chencang bindings.
//
// `ChencangCore` is the prebuilt XCFramework that ships the Rust staticlib +
// the uniffi-generated C FFI header. It's emitted by
// `cargo run -p xtask -- build-ios` and is gitignored — re-run that command
// after every facade change. The XCFramework's modulemap exposes a clang
// module named `chencangFFI` (see `swift/Sources/Chencang/chencang.swift`
// which does `import chencangFFI`).
//
// `Chencang` is the Swift wrapper target. It contains exactly one file —
// `chencang.swift`, regenerated by uniffi — which talks to the
// `chencangFFI` module from the binary target.
let package = Package(
    name: "Chencang",
    platforms: [
        .iOS(.v16),
        .macOS(.v12),
    ],
    products: [
        .library(name: "Chencang", targets: ["Chencang"]),
    ],
    targets: [
        .binaryTarget(
            name: "ChencangCore",
            path: "ChencangCore.xcframework"
        ),
        .target(
            name: "Chencang",
            dependencies: ["ChencangCore"],
            path: "Sources/Chencang",
            // chencangFFI.h / chencangFFI.modulemap also live in this dir
            // alongside chencang.swift (uniffi 0.31 emits them together).
            // The XCFramework already exposes the same `chencangFFI` clang
            // module, so we exclude the loose header/modulemap to avoid a
            // duplicate-module error.
            exclude: ["chencangFFI.h", "chencangFFI.modulemap"]
        ),
        .testTarget(
            name: "ChencangTests",
            dependencies: ["Chencang"],
            path: "Tests/ChencangTests",
            // Golden vectors (committed; regenerate via
            // `cargo run -p xtask -- golden-vectors`) ship as a bundled
            // resource so `Bundle.module.url(forResource:withExtension:)`
            // finds them in `GoldenVectorsTests`.
            resources: [
                .process("vectors.json"),
            ]
        ),
    ]
)
