import XCTest
@testable import Chencang

/// Mirrors `tests/facade_round_trip.rs::initiator_responder_round_trip_via_facade`
/// from `chencang-bindings`. The Swift surface is auto-generated by uniffi, so
/// this test is the canonical proof that the XCFramework wires up correctly:
/// it constructs identities + prekeys, runs the full handshake, opens two
/// `Session` objects, then verifies an encrypt → wire-text → decrypt round
/// trip across initiator (Bob) and responder (Alice).
final class SessionTests: XCTestCase {
    func testBasicRoundTrip() throws {
        // Generate a Bob (initiator) identity and a full Alice (responder)
        // pre-key bundle.
        let bobIk = SecretIdentity()
        let aliceIk = SecretIdentity()
        let aliceSpk = try SecretSignedPreKey(ik: aliceIk, spkVersion: 1)
        let aliceOpk = SecretOneTimePreKey(opkIndex: 1)

        let bundle = PreKeyBundle(
            ik: aliceIk.publicIdentity(),
            spk: aliceSpk.publicForm(),
            opk: aliceOpk.publicForm(),
            inviterUsername: "alice",
            inviteId: Data(repeating: 0x11, count: 16),
            pairingNonce: Data(repeating: 0x22, count: 16)
        )

        // Bob runs the initiator side of the handshake.
        let initOut = try deriveInitiatorHandshake(bobIk: bobIk, aliceBundle: bundle)

        // Alice runs the responder side from Bob's wire output. The session
        // root key on both sides must match byte-for-byte for a successful
        // PQXDH-style handshake.
        let srkAlice = try deriveResponderHandshake(
            aliceIk: aliceIk,
            aliceSpk: aliceSpk,
            aliceOpk: aliceOpk,
            bobIkPub: initOut.bobIdentityPublic,
            bobEkXPub: initOut.ekX25519Pub,
            bobEkKemPub: initOut.ekMlkemPub,
            kemCtToSpk: initOut.kemCtToSpk,
            kemCtToIk: initOut.kemCtToIk,
            kemCtToOpk: initOut.kemCtToOpk,
            pairingNonce: Data(repeating: 0x22, count: 16)
        )
        XCTAssertEqual(srkAlice, initOut.sessionRootKey,
                       "responder srk must equal initiator srk")

        // Open both halves of the session using the shared srk and a
        // synthetic 5-byte session id.
        let sid = Data([9, 9, 9, 9, 9])
        let bobSess = try Session.initiatorAfterHandshake(
            sessionRootKey: initOut.sessionRootKey,
            sessionId: sid,
            aliceIkPublic: aliceIk.publicIdentity(),
            ekX25519Secret: initOut.ekX25519Secret!,
            ekMlkemSecret: initOut.ekMlkemSecret!
        )
        let aliceSess = try Session.responderAfterHandshake(
            sessionRootKey: srkAlice,
            sessionId: sid,
            initiatorOutput: initOut
        )

        let plaintext = Data("hello chencang".utf8)
        let wire = try bobSess.encrypt(plaintext: plaintext)
        XCTAssertFalse(wire.isEmpty, "wire text must be non-empty")
        XCTAssertFalse(wire.contains("://"),
                       "encrypted wire text must not look like a URL")

        let decrypted = try aliceSess.decrypt(wireText: wire)
        XCTAssertEqual(decrypted, plaintext,
                       "decrypted bytes must equal original plaintext")
    }
}
